version: "3.8"
services:
  log_viewer:
    build: .
    ports:
      - "5000:5000"  # Maps container's port 5000 to host's port 5000
    volumes:
      - ./logs:/app/logs  # Mounts the local logs directory to the container
